Repository LikithKumarDK41/Nichi-Revamp, pull requests merged in 2025-07, with the labels that each got.

#5 fix in mobile sidebar
  assets/css/contact-us/index.css
  assets/css/global.css
  assets/css/header.css
  assets/js/main.js
  contact-us/index.html
  draft-back.css
  draft-back.js
  layout/header.html
  services/offshore-services/our-offerings.html
Labels: bug

#9 Refactor contact us page layout and styles for improved responsiveness and accessibility
  assets/css/about-us/index.css
  assets/css/contact-us/index.css
  assets/css/home.css
  assets/css/privacy-policy/privacy-policy.css
  assets/css/services/index.css
  assets/css/services/managed-it-services/odoo.css
  assets/css/services/offshore-services/DX/mobile-application-development.css
  assets/css/services/offshore-services/DX/smac-applications.css
  assets/css/services/offshore-services/Software-Testing-Migration/migration-legacy-system-modernization.css
  assets/css/services/offshore-services/Software-Testing-Migration/testing-quality-assurance.css
  assets/css/style.css
  contact-us/index.html
  index.html
  services/index.html
  services/managed-it-services/odoo.html
  services/offshore-services/DX/mobile-application-development.html
  services/offshore-services/Software-Testing-Migration/migration-legacy-system-modernization.html
  services/offshore-services/Software-Testing-Migration/testing-quality-assurance.html
Labels: enhancement, Design

#10 Services screens related changes
  assets/css/services/managed-it-services/index.css
  assets/css/services/offshore-services/index.css
  assets/css/services/offshore-services/it-support-services.css
  assets/css/services/product-development/index.css
  assets/css/style.css
  services/managed-it-services/index.html
  services/offshore-services/index.html
  services/onsite-consulting/index.html
  services/product-development/index.html
Labels: Design
